#!/bin/bash

function con() {
    local -i bytes=$1;
    if [[ $bytes -lt 1024 ]]; then
        echo "${bytes}B"
    elif [[ $bytes -lt 1048576 ]]; then
        echo "$(( (bytes + 1023)/1024 ))KB"
    elif [[ $bytes -lt 1073741824 ]]; then
        echo "$(( (bytes + 1048575)/1048576 ))MB"
    else
        echo "$(( (bytes + 1073741823)/1073741824 ))GB"
    fi
}

function cekvmess(){
  data=($(grep '^###' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq))
  [[ ! -e /etc/limit/vmess ]] && mkdir -p /etc/limit/vmess
  for user in ${data[@]}; do
    mkdir -p /tmp/quota
    data=$(xray api statsquery --server=127.0.0.1:10000 | grep -C 2 $user | \
           sed /"}"/d | sed /"{"/d | grep value | awk '{print $2}' | \
           sed 's/,//g; s/"//g' | sort)
    inb=$(echo "$data" | sed -n 1p)
    outb=$(echo "$data" | sed -n 2p) 
    quota0=$(( inb + outb ))
    if [[ -e /etc/limit/vmess/${user} ]]; then
      quota1=$(cat /etc/limit/vmess/${user})
      if [[ -n $quota1 ]]; then
        quota2=$(( quota0 + quota1 ))
        echo "${quota2}" > /etc/limit/vmess/"${user}"
      else
        echo "${quota0}" > /etc/limit/vmess/"${user}"
      fi
    else
      echo "${quota0}" > /etc/limit/vmess/"${user}"
    fi
    # reset counter setelah dicatat
    xray api stats --server=127.0.0.1:10000 \
      -name "user>>>${user}>>>traffic>>>downlink" -reset >/dev/null 2>&1
  done
}

function cekvless(){
  data=($(grep '^#&' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq))
  [[ ! -e /etc/limit/vless ]] && mkdir -p /etc/limit/vless
  for user in ${data[@]}; do
    mkdir -p /tmp/quota
    data=$(xray api statsquery --server=127.0.0.1:10000 | grep -C 2 $user | \
           sed /"}"/d | sed /"{"/d | grep value | awk '{print $2}' | \
           sed 's/,//g; s/"//g' | sort)
    inb=$(echo "$data" | sed -n 1p)
    outb=$(echo "$data" | sed -n 2p) 
    quota0=$(( inb + outb ))
    if [[ -e /etc/limit/vless/${user} ]]; then
      quota1=$(cat /etc/limit/vless/${user})
      if [[ -n $quota1 ]]; then
        quota2=$(( quota0 + quota1 ))
        echo "${quota2}" > /etc/limit/vless/"${user}"
      else
        echo "${quota0}" > /etc/limit/vless/"${user}"
      fi
    else
      echo "${quota0}" > /etc/limit/vless/"${user}"
    fi
    xray api stats --server=127.0.0.1:10000 \
      -name "user>>>${user}>>>traffic>>>downlink" -reset >/dev/null 2>&1
  done
}

function cektrojan(){
  data=($(grep '^#!' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq))
  [[ ! -e /etc/limit/trojan ]] && mkdir -p /etc/limit/trojan
  for user in ${data[@]}; do
    mkdir -p /tmp/quota
    data=$(xray api statsquery --server=127.0.0.1:10000 | grep -C 2 $user | \
           sed /"}"/d | sed /"{"/d | grep value | awk '{print $2}' | \
           sed 's/,//g; s/"//g' | sort)
    inb=$(echo "$data" | sed -n 1p)
    outb=$(echo "$data" | sed -n 2p) 
    quota0=$(( inb + outb ))
    if [[ -e /etc/limit/trojan/${user} ]]; then
      quota1=$(cat /etc/limit/trojan/${user})
      if [[ -n $quota1 ]]; then
        quota2=$(( quota0 + quota1 ))
        echo "${quota2}" > /etc/limit/trojan/"${user}"
      else
        echo "${quota0}" > /etc/limit/trojan/"${user}"
      fi
    else
      echo "${quota0}" > /etc/limit/trojan/"${user}"
    fi
    xray api stats --server=127.0.0.1:10000 \
      -name "user>>>${user}>>>traffic>>>downlink" -reset >/dev/null 2>&1
  done
}

function vmess(){
  while true; do
    sleep 30
    cekvmess
    data=($(grep '^###' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq))
    for user in ${data[@]}; do
      if [[ -e /etc/vmess/${user} ]]; then
        cekdulu=$(cat /etc/vmess/${user})
        if [[ -n $cekdulu ]]; then
          if [[ -e /etc/limit/vmess/${user} ]]; then
            pakai=$(cat /etc/limit/vmess/${user})
            if [[ $pakai -gt $cekdulu ]]; then
              exp=$(grep -w "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
              sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
              sed -i "/^### $user $exp/d" /etc/vmess/.vmess.db
              systemctl restart xray >/dev/null 2>&1
              rm -rf /etc/limit/vmess/${user}
            fi
          fi
        fi
      fi
    done
  done
}

function vless(){
  while true; do
    sleep 30
    cekvless
    data=($(grep '^#&' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq))
    for user in ${data[@]}; do
      if [[ -e /etc/vless/${user} ]]; then
        cekdulu=$(cat /etc/vless/${user})
        if [[ -n $cekdulu ]]; then
          if [[ -e /etc/limit/vless/${user} ]]; then
            pakai=$(cat /etc/limit/vless/${user})
            if [[ $pakai -gt $cekdulu ]]; then
              exp=$(grep -w "^#& $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
              sed -i "/^#& $user $exp/,/^},{/d" /etc/xray/config.json
              sed -i "/^### $user $exp/d" /etc/vless/.vless.db
              systemctl restart xray >/dev/null 2>&1
              rm -rf /etc/limit/vless/${user}
            fi
          fi
        fi
      fi
    done
  done
}

function trojan(){
  while true; do
    sleep 30
    cektrojan
    data=($(grep '^#!' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq))
    for user in ${data[@]}; do
      if [[ -e /etc/trojan/${user} ]]; then
        cekdulu=$(cat /etc/trojan/${user})
        if [[ -n $cekdulu ]]; then
          if [[ -e /etc/limit/trojan/${user} ]]; then
            pakai=$(cat /etc/limit/trojan/${user})
            if [[ $pakai -gt $cekdulu ]]; then
              exp=$(grep -w "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
              sed -i "/^#! $user $exp/,/^},{/d" /etc/xray/config.json
              sed -i "/^### $user $exp/d" /etc/trojan/.trojan.db
              systemctl restart xray >/dev/null 2>&1
              rm -rf /etc/limit/trojan/${user}
            fi
          fi
        fi
      fi
    done
  done
}

if [[ $1 == "vmess" ]]; then
  vmess
elif [[ $1 == "vless" ]]; then
  vless
elif [[ $1 == "trojan" ]]; then
  trojan
fi